# Generated by Django 5.0 on 2026-01-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='employee',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('divorced', 'Divorcé(e)'), ('widowed', 'Veuf/Veuve')], max_length=20, null=True, verbose_name='Situation matrimoniale'),
        ),
        migrations.AddField(
            model_name='employee',
            name='number_of_children',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse complète'),
        ),
    ]
