# Generated by Django 5.0 on 2026-01-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_birth_date_employee_city_employee_commune_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cni_document',
            field=models.FileField(blank=True, null=True, upload_to='employees/cni/', verbose_name="Carte Nationale d'Identité"),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name="Photo d'identité"),
        ),
    ]
