# Generated by Django 5.0 on 2026-01-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee_cni_document_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Masculin'), ('female', 'Féminin')], max_length=10, null=True, verbose_name='Sexe'),
        ),
    ]
