# Generated by Django 5.0 on 2026-02-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
    ]
