# Generated by Django 5.0 on 2026-02-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='direction',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Direction'),
        ),
    ]
