# Generated by Django 5.0 on 2026-02-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_employee_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cni_document',
        ),
        migrations.AddField(
            model_name='employee',
            name='cni_recto',
            field=models.FileField(blank=True, null=True, upload_to='employees/cni/', verbose_name='CNI Recto'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cni_verso',
            field=models.FileField(blank=True, null=True, upload_to='employees/cni/', verbose_name='CNI Verso'),
        ),
    ]
