# Generated by Django 5.0 on 2026-02-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_employee_cni_document_employee_cni_recto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matricule'),
        ),
    ]
