# Generated by Django 5.0 on 2026-02-12 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_direction_managerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_plain', models.CharField(max_length=200, verbose_name='Mot de passe')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Manager'), ('employee', 'Employé')], default='employee', max_length=20, verbose_name='Rôle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_record', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Mot de passe',
                'verbose_name_plural': 'Mots de passe',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
