# Generated by Django 5.0 on 2026-02-16 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_leave_manager_approved_by_alter_leave_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Entreprise', 'verbose_name_plural': 'Entreprises'},
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_managers', to='api.department', verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='api.department', verbose_name='Entreprise'),
        ),
    ]
