# Generated by Django 5.0 on 2026-02-21 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_encrypt_existing_passwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('7days', 'Rappel 7 jours avant le début'), ('eve', 'Rappel veille du début')], max_length=10, verbose_name="Type d'alarme")),
                ('trigger_date', models.DateField(verbose_name='Date de déclenchement')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.leave', verbose_name='Congé')),
            ],
            options={
                'verbose_name': 'Alarme de congé',
                'verbose_name_plural': 'Alarmes de congés',
                'ordering': ['trigger_date'],
                'unique_together': {('leave', 'notification_type')},
            },
        ),
    ]
